###

GET http://localhost:3000/

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "user2@gmail.com",
    "password": "234"
}

###

GET http://localhost:3000/post

###

POST http://localhost:3000/post
Authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NGI3OGYxNzRlYTNhYWM4NTc4MDMzMiIsImlhdCI6MTY5OTQ0OTM1MSwiZXhwIjoxNjk5NDUyOTUxfQ.kG0SMZF8cvVIM8TrQwxs2sll8ogZXl8P43WlBbBwQV4
Content-Type: application/json

{
    "message": "lll"
}

###

GET http://localhost:3000/book

###

POST http://localhost:3000/book
Content-Type: application/json

{
    "message": "lll"
}
